### PR TITLE
Introducing #core-dev channel

### PR DESCRIPTION
**Pull request by mbbroberg**
Adding `#core-dev` as a key channel going forward 💪

### CODE REVIEW

**Comment by majormoses** [comment]
Why is this not in just `#core`? Looking in slack that is kinda what I had in mind with core in the first place.

**Comment by mbbroberg** [comment]
@majormoses the scope of `#core` has been about being a user of Sensu rather than the development of the framework. It's a fair point, though I'd prefer to keep it super clear when we're coding on the project and when people are talking about using it.

**Comment by majormoses** [comment]
Understand and am fine with that I just wanted a defensible stance as there is generally very little traffic in core and tends to be more technical than generic "hey I need some help".

**Review by majormoses — APPROVED** [review]
LGTM

**Pull request merged**
