### PR TITLE
improve issue template to reflect process as discovered in #30

### PR DESCRIPTION
**Pull request by majormoses**
Feel free to wordsmith me and commit on my behalf @mbbroberg

### CODE REVIEW

**Comment by mbbroberg** [comment]
Will do @majormoses

**Comment by mbbroberg** [comment]
Made some edits to simplify (less words is gooder 👍) and amended. Also:

> In some cases not all maintainers may have access and they may ask you to transfer to a specific maintainer who has access to transfer org repos.

☝️ @majormoses this is behavior we can manage with sane permissions, so not needed in template.

**Comment by majormoses** [comment]
only admins are capable of transferring in, this means that either all maintainers are admins or we only assign admins to these requests.

**Comment by majormoses** [comment]
the thought behind the verbiage is that there is more work than simply transferring the repo and while I might transfer the repo I could hand off the rest to another maintainer who has access to everything else.

**Comment by mbbroberg** [comment]
@majormoses I didn't realize the intended scope. I'm working from the belief that Issue/PR template need to be as short and actionable as possible. 

What do you think of adding a checklist in the `replies.md` project since it sounds like a response from a maintainer to the issue (that will lend itself to automation later)?

**Comment by majormoses** [comment]
ya that could work.

**Pull request closed without merging**
