### PR TITLE
Refactor into informational repo

### LINKED ISSUE #24: Update scope of this repo
This repo is regularly used for migrating external plugins to this organization. It would be helpful to document that behavior in the README. It would also be good to remove unneeded code from here, especially with https://github.com/sensu-plugins/sensu-plugins-skel being the new home for a helper plugin.

### PR DESCRIPTION
**Pull request by mbbroberg**
Fixes #24 

* Removing unused code
* Providing context to new and old users alike
* Recommendations for how to contribute to Sensu plugins
* Shout out to the Skeleton repo as a great resource

### CODE REVIEW

**Comment by mbbroberg** [comment]
Don't merge but please start review when you're ready. Going to update the template.

**Comment by majormoses** [comment]
@mbbroberg I generally put `[WIP]` in the tile of the PR if its not ready for merge and then just change the title when I think its ready.

**Comment by majormoses** [comment]
so far it looks reasonable.

**Comment by eheydrick** [comment]
Look 👍. What about adding pointers to the mailing list and IRC? Would be a great way to get more folks helping with plugin use/development/issues, etc.

**Comment by mbbroberg** [comment]
Thanks gang - ready for review now. Two other things: 

* @majormoses I'm still used to using labels to indicate status, but I'll get used to using [wip] 
* @eheydrick love the idea of shoutout to community channels, though I'm not sure what we want to recommend just yet. I'd like to continue the discussion on what channels we want to commit to (e.g. are the email lists getting enough love or do we migrate to something more visible and managed like Discourse?). Let's add whatever our conclusion is to this repo after we decide.

**Review by majormoses — APPROVED** [review]
looks alright overall, on this lets merge fast and deal with adding more stuff later even if its slightly inaccurate.

**Pull request merged**
