### PR TITLE
Document PR process and guidelines

### PR DESCRIPTION
**Pull request by majormoses**
This is a very rough first attempt to document our current flow and some guidelines for users to ensure that they can get through the review process as quick as possible. This had *very* heavy influence from a similar [kubernetes doc](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md)

Signed-off-by: Ben Abrams <me@benabrams.it>

### CODE REVIEW

**Comment by majormoses** [comment]
This attempts to address some if not all of #52

**Comment by eheydrick** [comment]
Good stuff. Here's a few items I think we should add in the best practices section to increase the quality of PRs:

1) Is there an existing PR for this bug/feature? Check the open PRs before submitting a duplicate.
2) Is there an open issue for this bug/feature? If so link to it in the PR (e.g. Fixes #NN) in the body of the PR so the issue is linked and updated.
3) For bug fixes, include the before and after output so it's clear that the fix works. For example:

Before:
```
$ check-foo.rb
ExceptionBlagh
```

After:
```
$ check-foo.rb
CheckFoo OK
```

**Comment by majormoses** [comment]
@eheydrick I added what you wanted, for the sake of having something to link to I am gonna merge this and we can open up additional PRs to address issues and adding new things.

**Comment by mbbroberg** [comment]
This looks great @majormoses. Glad you did this!

**Comment by mbbroberg** [comment]
👏👏👏

**Pull request merged**
